FH = ../5.\ Fibonacci\ Heaps\ Ch.\ 19/
SSSP = ../9.\ Single-Source\ Shortest\ Paths\ Ch.\ 24/
all:
	g++ -std=c++11 test.cc floyd_warshall.cc johnson.cc $(SSSP)graph.cc $(SSSP)dijkstra.cc $(SSSP)bellman_ford.cc -I$(FH) -I$(SSSP) -o test